### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by HaroldMuvuti** [vaipatel/InfiniSolarP18#1]
Hallo Vai

Can this be adapted to run on a Raspberry Pi?

Maybe we can discuss.

Thank you 
Harold

**Comment by vaipatel** [comment]
Hi Harold,

I haven't done much stuff on a Rasberry Pi, but I think there shouldn't be too much of an issue with making the commands using [InfiniCommandMaker::makeCommand()](https://github.com/vaipatel/InfiniSolarP18/blob/391ecc2b8b8b6b22ce5e3f3d0dea0a3d094539e2/src/InfiniCommandMaker.h#L16) to populate the [InfiniCommandMaker::command](https://github.com/vaipatel/InfiniSolarP18/blob/391ecc2b8b8b6b22ce5e3f3d0dea0a3d094539e2/src/InfiniCommandMaker.h#L13).[val](https://github.com/vaipatel/InfiniSolarP18/blob/391ecc2b8b8b6b22ce5e3f3d0dea0a3d094539e2/src/InfiniMessageTypes.h#L19) char array.

This char array could then be sent over Serial ([example for connection/config on pimylifeup](https://pimylifeup.com/raspberry-pi-serial/)) from the Raspberry Pi to the inverter via a RS232-TTL converter, and the response could be read back and parsed.

The sending is what will have to be customized using a library like [WiringPi](http://wiringpi.com/) (or even just ["pure C"](https://blog.mbedded.ninja/programming/operating-systems/linux/linux-serial-ports-using-c-cpp/), although I am not that brave). It could probably also be done using [Qt](https://doc.qt.io/qt-5/qserialport.html) if that's already being used in the Pi.

To parse the received messages, one could then use some of [the (poorly designed) functions](https://github.com/vaipatel/InfiniSolarP18/blob/391ecc2b8b8b6b22ce5e3f3d0dea0a3d094539e2/src/InfiniResponseParser.h#L19-L22) in [InfiniResponseParser](https://github.com/vaipatel/InfiniSolarP18/blob/391ecc2b8b8b6b22ce5e3f3d0dea0a3d094539e2/src/InfiniResponseParser.h). These populate the [InfiniResponseParser::result](https://github.com/vaipatel/InfiniSolarP18/blob/391ecc2b8b8b6b22ce5e3f3d0dea0a3d094539e2/src/InfiniResponseParser.h#L15).[val](https://github.com/vaipatel/InfiniSolarP18/blob/391ecc2b8b8b6b22ce5e3f3d0dea0a3d094539e2/src/InfiniMessageTypes.h#L19) char array.

Essentially, the [InfiniCommandSender](https://github.com/vaipatel/InfiniSolarP18/blob/391ecc2b8b8b6b22ce5e3f3d0dea0a3d094539e2/src/InfiniCommandSender.h) is the part where Arduino specific code is used for sending Serial data, and which will have to be replaced with the appropriate code for communicating over Serial on Linux.

That probably didn't make a whole lot of sense given the paucity of documentation/implementation in this library, but hopefully it's a start!
